export {InicioComponent} from "./Inicio/Inicio.component"
export {EditorialComponent} from "./Editorial/Editorial.component"
export {ContactoComponent} from "./Contacto/Contacto.component"
export {SobreNosotrosComponent} from "./SobreNosotros/SobreNosotros.component"
export { AntoCVComponent } from "./SobreNosotros/AntoCV/AntoCV.component"
export { GastonCVComponent } from "./SobreNosotros/GastonCV/GastonCV.component"
export { KevinCVComponent } from "./SobreNosotros/KevinCV/KevinCV.component"
export { MarcosCVComponent } from "./SobreNosotros/MarcosCV/MarcosCV.component"
export { MaxiCVComponent } from "./SobreNosotros/MaxiCV/MaxiCV.component"
export { RodrigoCVComponent } from "./SobreNosotros/RodrigoCV/RodrigoCV.component"
export { YamilCVComponent } from "./SobreNosotros/YamilCV/YamilCV.component"

